### ISSUE TITLE
Lost data after docker compose down | docker compose up

### ISSUE THREAD

**Issue by erikmeliska** [camunda-community-hub/zeebe-redis-exporter#144]
Hi, when I use redis exporter with zeebe simple monitor, no matter if I set in the environment:
- ZEEBE_REDIS_MAX_TIME_TO_LIVE_IN_SECONDS=0
- ZEEBE_REDIS_DELETE_AFTER_ACKNOWLEDGE=false
- ZEEBE_REDIS_CLEANUP_CYCLE_IN_SECONDS=0
Every time after docker reload, data are gone, and simple monitor is empty.
I have a persistent volume for both redis and zeebe, zeebe keeps all just fine, but redis, even if I have dump.rdb in it, does not restore values, those are most probably cleaned up by exporter.
I expect it to restore values.
Without docker reload, values are persistent.
It seems, that when initialized, it runs cleanup, even if it should not.
When I have cleanup cycle set to default, and I reload container before 60 seconds, weirdly - data stays! But after another reload after 60 secs, data are gone :(
Do you have any hint, how to set it up properly?

Here is my compose file:
```
services:  
  zeebe:
    container_name: zeebe-broker
    image: ghcr.io/camunda-community-hub/zeebe-with-redis-exporter:8.4.4
    hostname: zeebe
    environment:
      - ZEEBE_REDIS_REMOTE_ADDRESS=redis://redis:6379
      - ZEEBE_REDIS_MAX_TIME_TO_LIVE_IN_SECONDS=0
      - ZEEBE_REDIS_DELETE_AFTER_ACKNOWLEDGE=false
      # - ZEEBE_REDIS_CLEANUP_CYCLE_IN_SECONDS=0
      - ZEEBE_LOG_LEVEL=debug
    env_file:
      - .env
    ports:
      - "26500:26500"
      - "9600:9600"
    networks:
      - onboarding_network
    volumes:
      - ./redis/application.yaml:/usr/local/zeebe/config/application.yaml
      - ./zeebe-data:/usr/local/zeebe/data

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - onboarding_network

  simple-monitor:
    container_name: zeebe-simple-monitor
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.7.2
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe-importer=redis
      - zeebe.client.worker.redis.connection=redis://redis:6379
    ports:
      - ${MONITOR_PORT}:8082
    depends_on:
      - zeebe
    networks:
      - onboarding_network
```

Here is the debug log after start:
```
io.camunda.zeebe.broker.exporter.redis - Starting Redis exporter with configuration: [remoteAddress='Optional[redis://redis]', useClusterClient='false', enabledValueTypes='', enabledRecordTypes='', format='protobuf', name='zeebe', cleanupCycleInSeconds=0, minTimeToLiveInSeconds=0, maxTimeToLiveInSeconds=0, deleteAfterAcknowledge=false, ioThreadPoolSize=8, batchSize=250, batchCycleMillis=500]

io.camunda.zeebe.broker.exporter - Set event filter for exporters: ExporterEventFilter{acceptRecordTypes={COMMAND_REJECTION=true, SBE_UNKNOWN=true, EVENT=true, NULL_VAL=true, COMMAND=true}, acceptValueTypes={MESSAGE_START_EVENT_SUBSCRIPTION=true, PROCESS_INSTANCE_MIGRATION=true, JOB_BATCH=true, MESSAGE=true, RESOURCE_DELETION=true, COMMAND_DISTRIBUTION=true, ESCALATION=true, MESSAGE_BATCH=true, USER_TASK=true, CHECKPOINT=true, DECISION=true, PROCESS_INSTANCE_MODIFICATION=true, DEPLOYMENT_DISTRIBUTION=true, COMPENSATION_SUBSCRIPTION=true, JOB=true, PROCESS_INSTANCE_RESULT=true, DECISION_REQUIREMENTS=true, SIGNAL=true, PROCESS_EVENT=true, TIMER=true, ERROR=true, DEPLOYMENT=true, PROCESS_MESSAGE_SUBSCRIPTION=true, FORM=true, PROCESS_INSTANCE=true, INCIDENT=true, SBE_UNKNOWN=true, VARIABLE_DOCUMENT=true, DECISION_EVALUATION=true, NULL_VAL=true, PROCESS=true, MESSAGE_SUBSCRIPTION=true, PROCESS_INSTANCE_BATCH=true, VARIABLE=true, PROCESS_INSTANCE_CREATION=true, SIGNAL_SUBSCRIPTION=true}}
```
